export const CATEGORIES = [
  'Computadores',
  'Telefonos',
  'UPSs',
  'Licencias',
  'Monitores',
  'Impresoras',
  'Escáneres',
];

// Campos específicos de cada categoría (además de nombre, cantidad y ubicación que son comunes)
export const CATEGORY_FIELDS = {
  Computadores: [
    { key: 'placa',                  label: 'Placa',                            type: 'text',     required: true,  placeholder: 'Ej: INV-2024-001' },
    { key: 'tipo',                   label: 'Tipo de Computador',               type: 'select',   required: true,  options: ['PC', 'All In One', 'Portátil'] },
    { key: 'fabricante',             label: 'Fabricante',                       type: 'text',     required: true,  placeholder: 'Ej: Dell' },
    { key: 'modelo',                 label: 'Modelo',                           type: 'text',     required: true,  placeholder: 'Ej: Latitude 5420' },
    { key: 'numero_serie',           label: 'Número de Serie',                  type: 'text',     required: true,  placeholder: 'Ej: DL-2024-001' },
    { key: 'estado',                 label: 'Estado',                           type: 'select',   required: true,  options: ['Excelente', 'Bueno', 'Funcional', 'Mal Estado'] },
    { key: 'red',                    label: 'Red',                              type: 'select',   required: true,  options: ['Ethernet', 'Wifi'] },
    { key: 'valor_compra',           label: 'Valor de Compra',                  type: 'number',   required: true,  placeholder: 'Ej: 1500000' },
    { key: 'fecha_compra',           label: 'Fecha de Compra',                  type: 'date',     required: true  },
    { key: 'tecnico_cargo',          label: 'Técnico a Cargo',                  type: 'text',     required: false, placeholder: 'Ej: Juan Pérez' },
    { key: 'encargado_alternativo',  label: 'Técnico Alternativo',  type: 'text',     required: false, placeholder: 'Ej: María García' },
    { key: 'comentarios',            label: 'Comentarios',                      type: 'textarea', required: false, placeholder: 'Observaciones adicionales...' },
  ],
  Telefonos: [
    { key: 'placa',                 label: 'Placa',                           type: 'text',     required: true,  placeholder: 'Ej: INV-2024-001' },
    { key: 'fabricante',            label: 'Fabricante',                      type: 'text',     required: true,  placeholder: 'Ej: Cisco' },
    { key: 'modelo',                label: 'Modelo',                          type: 'text',     required: true,  placeholder: 'Ej: IP Phone 8841' },
    { key: 'numero_serie',          label: 'Número de Serie',                 type: 'text',     required: true,  placeholder: 'Ej: CS-2024-001' },
    { key: 'estado',                label: 'Estado',                          type: 'select',   required: true,  options: ['Excelente', 'Bueno', 'Funcional', 'Mal Estado'] },
    { key: 'valor_compra',          label: 'Valor de Compra',                 type: 'number',   required: true,  placeholder: 'Ej: 400000' },
    { key: 'fecha_compra',          label: 'Fecha de Compra',                 type: 'date',     required: true  },
    { key: 'tecnico_cargo',         label: 'Técnico a Cargo',                 type: 'text',     required: false, placeholder: 'Ej: Juan Pérez' },
    { key: 'encargado_alternativo', label: 'Técnico Alternativo', type: 'text',     required: false, placeholder: 'Ej: María García' },
    { key: 'comentarios',           label: 'Comentarios',                     type: 'textarea', required: false, placeholder: 'Observaciones adicionales...' },
  ],
  UPSs: [
    { key: 'placa',                 label: 'Placa',                           type: 'text',     required: true,  placeholder: 'Ej: INV-2024-001' },
    { key: 'fabricante',            label: 'Fabricante',                      type: 'text',     required: true,  placeholder: 'Ej: APC' },
    { key: 'modelo',                label: 'Modelo',                          type: 'text',     required: true,  placeholder: 'Ej: Back-UPS 1500' },
    { key: 'numero_serie',          label: 'Número de Serie',                 type: 'text',     required: true,  placeholder: 'Ej: APC-2024-001' },
    { key: 'tipo_ups',              label: 'Tipo de UPS',                     type: 'select',   required: true,  options: ['Interactiva', 'Online de Doble Conversión'] },
    { key: 'estado',                label: 'Estado',                          type: 'select',   required: true,  options: ['Excelente', 'Bueno', 'Funcional', 'Mal Estado'] },
    { key: 'valor_compra',          label: 'Valor de Compra',                 type: 'number',   required: true,  placeholder: 'Ej: 600000' },
    { key: 'fecha_compra',          label: 'Fecha de Compra',                 type: 'date',     required: true  },
    { key: 'tecnico_cargo',         label: 'Técnico a Cargo',                 type: 'text',     required: false, placeholder: 'Ej: Juan Pérez' },
    { key: 'encargado_alternativo', label: 'Técnico Alternativo', type: 'text',     required: false, placeholder: 'Ej: María García' },
    { key: 'comentarios',           label: 'Comentarios',                     type: 'textarea', required: false, placeholder: 'Observaciones adicionales...' },
  ],
  Licencias: [
    { key: 'numero_serie',          label: 'Número de Serie',                 type: 'text',     required: true,  placeholder: 'Ej: XXXXX-XXXXX-XXXXX' },
    { key: 'placa',                 label: 'Placa',                           type: 'text',     required: true,  placeholder: 'Ej: INV-2024-001' },
    { key: 'fabricante',            label: 'Fabricante',                      type: 'text',     required: true,  placeholder: 'Ej: Microsoft' },
    { key: 'valor_compra',          label: 'Valor de Compra',                 type: 'number',   required: true,  placeholder: 'Ej: 500000' },
    { key: 'fecha_compra',          label: 'Fecha de Compra',                 type: 'date',     required: true  },
    { key: 'encargado_alternativo', label: 'Técnico Alternativo', type: 'text',     required: false, placeholder: 'Ej: María García' },
    { key: 'comentarios',           label: 'Comentarios',                     type: 'textarea', required: false, placeholder: 'Observaciones adicionales...' },
  ],
  Monitores: [
    { key: 'placa',                 label: 'Placa',                           type: 'text',     required: true,  placeholder: 'Ej: INV-2024-001' },
    { key: 'fabricante',            label: 'Fabricante',                      type: 'text',     required: true,  placeholder: 'Ej: Samsung' },
    { key: 'modelo',                label: 'Modelo',                          type: 'text',     required: true,  placeholder: 'Ej: Odyssey G5' },
    { key: 'numero_serie',          label: 'Número de Serie',                 type: 'text',     required: true,  placeholder: 'Ej: SM-2024-001' },
    { key: 'tamano',                label: 'Tamaño',                          type: 'text',     required: true,  placeholder: 'Ej: 27"' },
    { key: 'tipo_panel',            label: 'Tipo de Panel',                   type: 'select',   required: true,  options: ['LCD', 'LED', 'Plasma', 'OLED', 'Curvo'] },
    { key: 'estado',                label: 'Estado',                          type: 'select',   required: true,  options: ['Excelente', 'Bueno', 'Funcional', 'Mal Estado'] },
    { key: 'valor_compra',          label: 'Valor de Compra',                 type: 'number',   required: true,  placeholder: 'Ej: 800000' },
    { key: 'fecha_compra',          label: 'Fecha de Compra',                 type: 'date',     required: true  },
    { key: 'tecnico_cargo',         label: 'Técnico a Cargo',                 type: 'text',     required: false, placeholder: 'Ej: Juan Pérez' },
    { key: 'encargado_alternativo', label: 'Técnico Alternativo', type: 'text',     required: false, placeholder: 'Ej: María García' },
    { key: 'comentarios',           label: 'Comentarios',                     type: 'textarea', required: false, placeholder: 'Observaciones adicionales...' },
  ],
  Impresoras: [
    { key: 'placa',                 label: 'Placa',                           type: 'text',     required: true,  placeholder: 'Ej: INV-2024-001' },
    { key: 'fabricante',            label: 'Fabricante',                      type: 'text',     required: true,  placeholder: 'Ej: HP' },
    { key: 'modelo',                label: 'Modelo',                          type: 'text',     required: true,  placeholder: 'Ej: LaserJet Pro M404n' },
    { key: 'numero_serie',          label: 'Número de Serie',                 type: 'text',     required: true,  placeholder: 'Ej: HP-2024-001' },
    { key: 'tipo_impresora',        label: 'Tipo de Impresora',               type: 'select',   required: true,  options: ['Carnet', 'Cinta', 'Inyección', 'Inyección continua', 'Láser', 'Láser Color', 'Térmica'] },
    { key: 'puertos',               label: 'Puertos',                         type: 'select',   required: true,  options: ['Serial', 'Paralelo', 'USB', 'Ethernet', 'Wifi'] },
    { key: 'estado',                label: 'Estado',                          type: 'select',   required: true,  options: ['Excelente', 'Bueno', 'Funcional', 'Mal Estado'] },
    { key: 'valor_compra',          label: 'Valor de Compra',                 type: 'number',   required: true,  placeholder: 'Ej: 900000' },
    { key: 'fecha_compra',          label: 'Fecha de Compra',                 type: 'date',     required: true  },
    { key: 'tecnico_cargo',         label: 'Técnico a Cargo',                 type: 'text',     required: false, placeholder: 'Ej: Juan Pérez' },
    { key: 'encargado_alternativo', label: 'Técnico Alternativo', type: 'text',     required: false, placeholder: 'Ej: María García' },
    { key: 'comentarios',           label: 'Comentarios',                     type: 'textarea', required: false, placeholder: 'Observaciones adicionales...' },
  ],
  Escáneres: [
    { key: 'placa',                 label: 'Placa',                           type: 'text',     required: true,  placeholder: 'Ej: INV-2024-001' },
    { key: 'fabricante',            label: 'Fabricante',                      type: 'text',     required: true,  placeholder: 'Ej: Epson' },
    { key: 'modelo',                label: 'Modelo',                          type: 'text',     required: true,  placeholder: 'Ej: WorkForce ES-400' },
    { key: 'numero_serie',          label: 'Número de Serie',                 type: 'text',     required: true,  placeholder: 'Ej: EP-2024-001' },
    { key: 'puertos',               label: 'Puertos',                         type: 'select',   required: true,  options: ['Serial', 'Paralelo', 'USB', 'Ethernet', 'Wifi'] },
    { key: 'estado',                label: 'Estado',                          type: 'select',   required: true,  options: ['Excelente', 'Bueno', 'Funcional', 'Mal Estado'] },
    { key: 'uso',                   label: 'Uso',                             type: 'select',   required: true,  options: ['Grupal', 'Local'] },
    { key: 'valor_compra',          label: 'Valor de Compra',                 type: 'number',   required: true,  placeholder: 'Ej: 900000' },
    { key: 'fecha_compra',          label: 'Fecha de Compra',                 type: 'date',     required: true  },
    { key: 'tecnico_cargo',         label: 'Técnico a Cargo',                 type: 'text',     required: false, placeholder: 'Ej: Juan Pérez' },
    { key: 'encargado_alternativo', label: 'Técnico Alternativo', type: 'text',     required: false, placeholder: 'Ej: María García' },
    { key: 'comentarios',           label: 'Comentarios',                     type: 'textarea', required: false, placeholder: 'Observaciones adicionales...' },
  ],
};

// Configuración por categoría: comportamiento del modal
export const CATEGORY_CONFIG = {
  Computadores: { hideQuantity: true, requireEncargado: true },
  Monitores:    { hideQuantity: true, requireEncargado: true },
  Licencias:    { hideQuantity: true, requireEncargado: true },
  Impresoras:   { hideQuantity: true, requireEncargado: true },
  UPSs:         { hideQuantity: true, requireEncargado: true },
  Telefonos:    { hideQuantity: true, requireEncargado: true },
  Escáneres:    { hideQuantity: true, requireEncargado: true },
};

